### ISSUE TITLE
Should be able to set a default duration in config.ru

### ISSUE THREAD

**Issue by barnaclebarnes** [vrish88/sinatra_cyclist#1]
it would be good if you could set the duration for the cycle on the config.ru file instead of having to put this in the url.

**Comment by vrish88** [comment]
Good suggestion. Would the param on url still be useful if this were in place?

**Comment by barnaclebarnes** [comment]
Yes I think it would still be useful as an override. You could also have per dashboard durations possibly. `[ dash1: 30,  dash2: 60]`. Not sure ow easy this would be but may be something that is useful when you have dashboards that you want to show for longer.

**Comment by kevintuhumury** [comment]
This has be fixed in: https://github.com/vrish88/sinatra_cyclist/pull/6
