### ISSUE TITLE
Cycle duration for Dashing does not work

### ISSUE THREAD

**Issue by tdonelson** [vrish88/sinatra_cyclist#5]
First of all, great addition here.

I am having an issue when using it with Dashing, though. It seems that currently, the "duration" parameter does not affect the time to cycle between dashboards. No matter what number I provide, the default cycle time is always used.

I did see there was an update with this issue here: https://github.com/vrish88/sinatra_cyclist/pull/3

It appears that jeromegn made a fix after the pull was completed, but the fix was never incorporated. Any chance that could be pulled in?

**Comment by kevintuhumury** [comment]
I noticed the same and added an improvement, see: https://github.com/vrish88/sinatra_cyclist/pull/6. Maybe this can be merged instead?

**Comment by vrish88** [comment]
Those pull requests have been merged so closing this one.
